language: node_js
node_js:
- 7
- 8
- 9
- stable
services: mongodb
deploy:
  provider: npm
  email: hello@trailsjs.io
  api_key:
    secure: Rk+XRjuj+kDZj56KSSxVdw4fSfHquX4LVnPwMSRrzhef/VNa4lobwFFdqjzFNTTbyc7AI/hAiRLpDRiEF7EnmLD28YSnCGczLXtwYdtjETpvp8JEH+oXa80VkP0rcrT/VDCVvYpO62j3qpKiDq19/91ai+bZiOsgcxkUamkcKTZ/P8JkvBoRChTxnbqcIxJb3qzRd13FMc7lYFBmULBOvV39Z63yaQ0szc4THhOGe5Wxmo5eAKhkfug6U2w44/H91RFAXFqFI5vLQxArv5b3cnT1GncgUb2R+z5mhJ8UM938gmJQXT6MJcTSEvhXahIJ3+C/xby1SbnMam5q5twbogpA3Sm9X/HDGrW7yaBgMNLE4DevdEyGDX4uKi1Gir6WUtdBxC5Jecu7qam1W1GTcpG7vFPbf7EeNuN8/SVaU+oHxh1D21AtVG12UzIa1IlRY7mZnUec7pFSadVem+Pe56ien5CHKuD5ySybjOGjIdkcBhza2a6VTm84/0CLODetSAZv3NpSbQAgoIA479H8o0PuTDU1bLQ9TQRRpEpAf6kvvW0tbs/WFYdYBKw+OJwdIHUedKCBfY6ej44g/8LBmHvqrO4TcunDN62WAKtzZ3TNlZDfRlFuZobzcUY2DBSHBY/CKYLILzDipWijcoPizzexKE2rKJK0vxsMttymLR0=
  on:
    tags: true
    repo: trailsjs/trailpack-mongoose
    node: stable
